# -*- coding: utf-8 -*-
"""EE21MTECH12003_HW1_Exercise_1.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v9M3kZvDbq8tWCOO2XwOzjQFXBzjNLAF
"""

import numpy as np
B = np.random.randint(4, size=(6, 4))

def gram_schmidt_orth(A):
  ortn_b=[]
  for i in A: 
    w = i - np.sum( (i@b)*b  for b in ortn_b )
    #print(i,np.dot(i,b),np.array(ortn_b).shape)
    if (w > 1e-10).any():  
        ortn_b.append((w)/np.linalg.norm(w))
  return np.array(ortn_b)

#b=np.array([[1,-1,1],[1,0,1],[1,1,2]])
h=gram_schmidt_orth(B)
print("orthonormal matrix using Gram-Schmidt orthonormalization:\n",h)